version: 2.1
jobs: 
  build-and-test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: pip install coverage sinon
      - run: coverage run --omit=/home -m unittest discover -s test -v
      - run: coverage report -m

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-and-test